=== martian-a/j-grid/db/seeds/event.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="event">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element name="name" type="xs:string" />
    			<xs:element name="hashtag" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
    			<xs:element name="rooms" type="roomList" />
    			<xs:element name="timeslots" type="timeslotList" />
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
    
    <xs:complexType name="roomList">
    	<xs:sequence>
    		<xs:element ref="room" maxOccurs="unbounded" />    		
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="timeslotList">
    	<xs:sequence>
    		<xs:choice maxOccurs="unbounded">
    			<xs:element ref="timeslot" />
				<xs:element ref="break" />
			</xs:choice>    		    		
    	</xs:sequence>
    </xs:complexType>
    
    <xs:element name="room">
    	<xs:complexType mixed="true">
    	    <xs:sequence>   	
				<xs:element name="name" type="xs:string" minOccurs="0" />
				<xs:element name="description" type="xs:string" minOccurs="0" />
				<xs:element name="facilities" type="xs:string" minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="shortcode" type="shortcode" use="required" />
    		<xs:attribute name="capacity" type="xs:string" /> 
    		<xs:attribute name="inGrid" type="xs:boolean" default="true" />
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="timeslot">
    	<xs:complexType mixed="true">
    		<xs:sequence>
    			<xs:element name="name" type="xs:string" minOccurs="0" />
    			<xs:element ref="talk" minOccurs="0" />
    		</xs:sequence>    		    		
    		<xs:attribute name="start" type="xs:dateTime" />
    		<xs:attribute name="end" type="xs:dateTime" />
    		<xs:attribute name="duration" type="xs:duration" />
    		<xs:attribute name="repeat" type="xs:integer" />
    		<xs:attribute name="break" type="xs:duration" /> 
    		<xs:attribute name="locked" type="xs:boolean" />   		
    	</xs:complexType>
    </xs:element>	
    
	<xs:element name="break">
    	<xs:complexType>
    		<xs:attribute name="duration" type="xs:duration" />	    			    				
    	</xs:complexType>	
    </xs:element>
    
    <xs:simpleType name="shortcode">
    	<xs:restriction base="xs:string">
    		<xs:length value="3" fixed="true" />
    		<xs:whiteSpace value="collapse" fixed="true" />
    	</xs:restriction>
    </xs:simpleType>
    
    <xs:element name="talk">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element name="room">
    				<xs:complexType>
    					<xs:attribute name="ref" type="shortcode" use="required" />
    				</xs:complexType>
    			</xs:element>
    			<xs:element name="title">
    				<xs:complexType>
    					<xs:attribute name="inherit" type="xs:boolean" />
    				</xs:complexType>
    			</xs:element>
    			<xs:element name="description" type="xs:string" minOccurs="0" />
    			<xs:element name="speaker" type="xs:string" minOccurs="0" />    				
    		</xs:sequence>
    		<xs:attribute name="locked" type="xs:boolean" />
    	</xs:complexType>
    </xs:element>
    
</xs:schema>

=== martian-a/j-grid/db/seeds/bcl9.xml
<?xml version="1.0" encoding="UTF-8"?>
<event 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="event.xsd"
>
	<name>BarCamp London 9</name>
	<hashtag>bcl9</hashtag>
	<rooms>
		<room shortcode="any" capacity="250" inGrid="false">
			<name>Everywhere</name>
			<description>Any and all rooms (assuming it's not out-of-bounds and there's no other talk scheduled in it).</description>
		</room>
		<room shortcode="hel" capacity="250" inGrid="false">
			<name>The Hellmouth</name>
			<description>The common room.  In the basement, down the stairs and to the left.</description>
			<facilities></facilities>
		</room>
		<room shortcode="cem" capacity="60">
			<name>0001 Cemetery Lane</name>
			<description>Large room in the basement.  To your right, behind you as you come down the stairs (near the zombie-infested toilets, practically under the stairs).</description>
			<facilities>Teaching pod, intermittent Lecture capture.</facilities>
		</room>								
	</rooms>
	<timeslots>
		<timeslot start="2011-10-29T09:30:00Z" duration="PT40M" locked="true">
			<name>Opening Talk</name>			
			<talk>
				<room ref="hel" />			
				<title inherit="true" />
				<description>Welcome to BarcampLondon9!</description>
				<speaker>The Crew</speaker>
			</talk>
		</timeslot>
		<timeslot duration="PT20M" locked="true">
			<name>Grid Population</name>
			<talk>
				<room ref="hel" />			
				<title inherit="true" />
				<description>Add your talk to the grid</description>
				<speaker>You</speaker>
			</talk>						
		</timeslot>
		<timeslot duration="PT30M" />
		<break duration="PT5M" />
		<timeslot duration="PT25M" repeat="3" break="PT5M" />
		<timeslot duration="PT60M" locked="true">
			<name>Lunch</name>	
			<talk>
				<room ref="hel" />			
				<title inherit="true" />
			</talk>					
		</timeslot>
		<timeslot duration="PT30M" repeat="4" break="PT5M" />
		<timeslot duration="PT30M" locked="true">
			<name>Tea Break</name>		
			<talk>
				<room ref="hel" />			
				<title inherit="true" />
			</talk>						
		</timeslot>
		<timeslot duration="PT25M" repeat="4" break="PT5M" />			
		<timeslot duration="PT90M" locked="true">
			<name>Dinner</name>		
			<talk>
				<room ref="hel" />			
				<title inherit="true" />
			</talk>						
		</timeslot>		
		<timeslot duration="PT20M" repeat="2" break="PT10M" />
		<timeslot end="2011-10-30T08:00:00Z" locked="true">
			<name>Games, etc.</name>
			<talk>
				<room ref="any" />			
				<title inherit="true" />
			</talk>								
		</timeslot>
		<timeslot duration="PT120M" locked="true">
			<name>Breakfast</name>
			<talk>
				<room ref="hel" />			
				<title inherit="true" />
			</talk>								
		</timeslot>
		<timeslot duration="PT30M" repeat="4" break="PT10M" />
		<break duration="PT10M" />
		<timeslot duration="PT20M" />
		<timeslot duration="PT60M" locked="true">
			<name>Lunch</name>
			<talk>
				<room ref="hel" />			
				<title inherit="true" />
			</talk>								
		</timeslot>
		<timeslot duration="PT25M" repeat="4" break="PT5M" />
		<break duration="PT5M" />
		<timeslot duration="PT15M" locked="true">
			<name>Closing Talk</name>
			<talk>
				<room ref="hel" />			
				<title inherit="true" />
			</talk>								
		</timeslot>
		<timeslot duration="PT30M" locked="true">
			<name>Tidy-up</name>
			<talk>
				<room ref="any" />			
				<title inherit="true" />
			</talk>								
		</timeslot>		
	</timeslots>	
</event>

=== martian-a/j-grid/db/seeds/test/timeslots/break.xml
<?xml version="1.0" encoding="UTF-8"?>
<event 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="../../event.xsd"	
>
	<name>Test Event</name>
	<hashtag>test</hashtag>
	<rooms>
		<room shortcode="any" capacity="250" inGrid="false">
			<name>Everywhere</name>
			<description>Any and all rooms (assuming it's not out-of-bounds and there's no other talk scheduled in it).</description>
		</room>									
	</rooms>
	<timeslots>
		<timeslot start="2011-10-29T09:30:00Z" duration="PT30M" break="PT15M" />
		<timeslot duration="PT20M" break="PT10M" />
		<timeslot duration="PT10M" break="PT5M" />
		<break duration="PT5M" />
		<timeslot duration="PT10M" break="PT5M" />
		<timeslot duration="PT10M" />
		<break duration="PT5M" />
		<timeslot duration="PT10M" break="PT5M" />
	</timeslots>	
</event>

=== martian-a/j-grid/db/seeds/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<event 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="event.xsd"
>
	<name>Test Event</name>
	<hashtag>test</hashtag>
	<rooms>
		<room shortcode="any" capacity="250" inGrid="false">
			<name>Everywhere</name>
			<description>Any and all rooms (assuming it's not out-of-bounds and there's no other talk scheduled in it).</description>
		</room>
		<room shortcode="com" capacity="250" inGrid="false">
			<name>Common Room</name>
			<description>In the basement, down the stairs and to the left.</description>
		</room>
		<room shortcode="rm1" capacity="60">
			<name>Room One</name>
			<description>A room that holds approximately sixty people and is equipped with a projector and whiteboard.</description>
			<facilities>Projector, Whiteboard.</facilities>
		</room>								
	</rooms>
	<timeslots>
		<timeslot start="2011-10-29T09:30:00Z" duration="PT30M" />
		<timeslot duration="PT20M" />
		<timeslot duration="PT10M" />
	</timeslots>	
</event>
